### ISSUE TITLE
Running fails in OS X, Node v0.12.2

### ISSUE THREAD

**Issue by sean-clayton** [magalhini/firstaidgit#2]
I installed all Node dependencies using `npm install`. I then ran `npm run start` per instructions and this is the output:

```sh
➜  firstaidgit git:(master) npm run start

> webpack-another@1.0.0 start /Users/sean/projects/firstaidgit
> webpack-dev-server --hot --progress --colors

 70% 1/1 build moduleshttp://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from /Users/sean/projects/firstaidgit
Hash: 4175e2c05ee35505d7b2
Version: webpack 1.8.5
Time: 1068ms
chunk    {0} app.4175e2c05ee35505d7b2.js (app) 2.64 kB [rendered]
    [0] multi app 40 bytes {0} [built] [1 error]
    [1] (webpack)/hot/dev-server.js 1.79 kB {0} [built]
    [3] (webpack)/hot/log-apply-result.js 813 bytes {0} [built]

ERROR in Loader /Users/sean/projects/firstaidgit/node_modules/babel/lib/babel/api/node.js didn't return a function
 @ multi app
webpack: bundle is now VALID.
TypeError: Failed to decode param '/%7B%=o.htmlWebpackPlugin.options.publicPath%7D%7B%=o.webpack.assetsByChunkName.app[1]%7D'
    at decode_param (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/layer.js:162:15)
    at Layer.match (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/layer.js:136:11)
    at matchLayer (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/index.js:545:18)
    at next (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/index.js:206:15)
    at /Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/middleware.js:146:12
    at ready (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/middleware.js:76:20)
    at webpackDevMiddleware (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/middleware.js:133:3)
    at Layer.handle [as handle_request] (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/index.js:302:13)
    at /Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/index.js:270:7
TypeError: Failed to decode param '/%7B%=o.htmlWebpackPlugin.options.webpackDevServer%7D'
    at decode_param (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/layer.js:162:15)
    at Layer.match (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/layer.js:136:11)
    at matchLayer (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/index.js:545:18)
    at next (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/index.js:206:15)
    at /Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/middleware.js:146:12
    at ready (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/middleware.js:76:20)
    at webpackDevMiddleware (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/middleware.js:133:3)
    at Layer.handle [as handle_request] (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/index.js:302:13)
    at /Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/index.js:270:7
TypeError: Failed to decode param '/%7B%=o.htmlWebpackPlugin.assets[chunk]%7D'
    at decode_param (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/layer.js:162:15)
    at Layer.match (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/layer.js:136:11)
    at matchLayer (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/index.js:545:18)
    at next (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/index.js:206:15)
    at /Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/middleware.js:146:12
    at ready (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/middleware.js:76:20)
    at webpackDevMiddleware (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/middleware.js:133:3)
    at Layer.handle [as handle_request] (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/index.js:302:13)
    at /Users/sean/projects/firstaidgit/node_modules/webpack-dev-server/node_modules/express/lib/router/index.js:270:7
```

**Comment by magalhini** [comment]
Oh, I'll have to try this myself. Apparently you're not the only one having this issue, so I'm going to debug it as soon as I get a chance. Thanks for letting me know!

**Comment by tcelestino** [comment]
@magalhini in Ubuntu (14.04 LTS) this message below:

```bash
> FirstAidGit@1.0.0 start /home/tcfarias/workspace/my projects/firstaidgit
> webpack-dev-server --hot --progress --colors

 70% 1/1 build modules
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at net.js:1143:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:121:9)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```

**Comment by ahmadalibaloch** [comment]
I ran into same problem... any solution?

**Comment by magalhini** [comment]
I'm running into the same issue too myself, and my guess is the updated node 4.x build that's failing on a few dependencies, namely node-sass. I've been doing my best to fix this but apparently it's an issue with this library — might actually need to downgrade node... :(
